name: DS Python Package CI

on: [workflow_call]

jobs:
  linters_and_tests:
    name: linters & tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.0
      - name: Setup Python
        uses: actions/setup-python@v3.0.0
        with:
          python-version: 3.10.2
      - name: Install dependencies
        id: install_dependencies
        run: |
          # Install the linters for the case there is no 'requirements' file. If we do have one
          # The secound installation will override it with the pinned version.
          pip install black flake8 flake8-bugbear pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with black
        if: ${{ always() }}
        run: |
          if [ -f black.toml ]; then
            black --config black.toml --check .
          else 
            black --line-length 100 --check .
          fi
      - name: Lint with flake8
        if: ${{ always() }}
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --show-source --statistics
      - name: Test with pytest
        if: ${{ always() }}
        run: |
          if [ -d tests ]; then 
            pytest -ra -q tests;
          else
            echo "No 'tests' dir was found. Skipping."
          fi
